/**
 * Weather & Sky — Client half.
 *
 * Registers a full-screen, pointer-transparent overlay into `shell.overlay`.
 * Weather data is fetched from the Host through the generated Typert remote
 * binding (`ctx.remote.weatherSky.getWeather()`), polled every 15 seconds.
 */
import type { Context } from '@deepseek-ai/cordis'
import * as React from 'react'
import type {} from '@deepseek-ai/dsh-client-runtime/client'
import type {} from '@deepseek-ai/dsh-client-ui-slots'
import type {} from '@deepseek-ai/dsh-api-remotes/client'
// Generated by the Typert build from the Host's `@Remote('getWeather')` method.
import type {} from '@deepseek-ai/dsh-weather-sky/remote'
import type { WeatherSnapshot } from '../types.ts'

const CSS = `
.ws-sky{position:fixed;inset:0;pointer-events:none;overflow:hidden;z-index:0;}
.ws-sky *{pointer-events:none;}
.ws-layer{position:absolute;inset:0;overflow:hidden;}
.ws-tint{position:absolute;inset:0;transition:opacity 2s ease;}
.ws-celestial{position:absolute;width:96px;height:96px;transform:translate(-50%,-50%);opacity:.75;}
.ws-sun{position:absolute;top:12px;left:12px;width:72px;height:72px;border-radius:50%;
  background:radial-gradient(circle at 35% 35%,#fff8d8,#ffd54f 55%,#ffb300);
  box-shadow:0 0 40px 16px rgba(255,200,80,.5),0 0 90px 40px rgba(255,180,60,.22);
  animation:ws-sun-pulse 5s ease-in-out infinite;}
@keyframes ws-sun-pulse{0%,100%{transform:scale(1);opacity:.9}50%{transform:scale(1.07);opacity:1}}
.ws-moon{position:absolute;top:15px;left:15px;width:66px;height:66px;border-radius:50%;
  background:radial-gradient(circle at 40% 38%,#f5f7ff,#ccd4ee 58%,#a7b0d4);}
.ws-star{position:absolute;border-radius:50%;background:#fff;animation:ws-twinkle 3s ease-in-out infinite;}
@keyframes ws-twinkle{0%,100%{opacity:.12}50%{opacity:.85}}
.ws-cloud{position:absolute;background:rgba(255,255,255,.55);border-radius:100px;filter:blur(3px);animation:ws-drift linear infinite;}
.ws-cloud.dark{background:rgba(88,96,124,.5);}
.ws-cloud .puff{position:absolute;background:inherit;border-radius:50%;}
.ws-cloud .p1{width:56%;height:140%;left:10%;top:-64%;}
.ws-cloud .p2{width:46%;height:128%;left:42%;top:-46%;}
.ws-cloud .p3{width:62%;height:118%;left:26%;top:-32%;}
@keyframes ws-drift{from{transform:translateX(-35vw)}to{transform:translateX(135vw)}}
.ws-rain{position:absolute;top:-8%;width:2px;border-radius:2px;
  background:linear-gradient(to bottom,rgba(160,195,255,0),rgba(140,180,250,.85));animation:ws-rain linear infinite;}
@keyframes ws-rain{to{transform:translateY(120vh)}}
.ws-snow{position:absolute;top:-6%;border-radius:50%;background:#fff;opacity:.85;animation:ws-snow linear infinite;}
@keyframes ws-snow{0%{transform:translate(0,0)}100%{transform:translate(34px,120vh)}}
.ws-flash-screen{position:absolute;inset:0;background:rgba(210,225,255,.18);opacity:0;}
.ws-flash-screen.flash{animation:ws-flash 1.7s ease-out;}
.ws-bolt{position:absolute;top:0;left:0;width:100%;height:62%;opacity:0;}
.ws-bolt.flash{animation:ws-flash 1.7s ease-out;}
@keyframes ws-flash{0%{opacity:0}5%{opacity:.95}9%{opacity:.15}13%{opacity:.8}20%{opacity:0}100%{opacity:0}}
.ws-fog{position:absolute;left:-12%;right:-12%;height:130px;border-radius:50%;
  background:radial-gradient(ellipse at center,rgba(222,227,238,.5),rgba(222,227,238,0));
  filter:blur(12px);animation:ws-fog 20s ease-in-out infinite;}
@keyframes ws-fog{0%,100%{transform:translateX(-5%)}50%{transform:translateX(5%)}}
.ws-chip{position:fixed;right:14px;bottom:14px;display:flex;align-items:center;gap:7px;
  max-width:300px;padding:7px 11px;border-radius:999px;font-size:12px;line-height:1.2;color:rgba(255,255,255,.92);
  background:rgba(18,24,44,.38);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);
  border:1px solid rgba(255,255,255,.14);box-shadow:0 4px 18px rgba(0,0,0,.18);
  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
.ws-chip-icon{font-size:15px;line-height:1;}
.ws-chip-text{overflow:hidden;text-overflow:ellipsis;}
`

type Timer = { interval: (cb: () => void, ms: number) => () => void }

function makeRain(intensity: number): Array<Record<string, string>> {
  const count = Math.round(28 + intensity * 92)
  const out: Array<Record<string, string>> = []
  for (let i = 0; i < count; i++) {
    const len = 14 + intensity * 26 + Math.random() * 12
    const dur = (0.55 + (1 - intensity) * 0.95) * (0.7 + Math.random() * 0.6)
    out.push({
      left: `${Math.random() * 100}%`,
      height: `${len.toFixed(0)}px`,
      animationDuration: `${dur.toFixed(2)}s`,
      animationDelay: `${(-Math.random() * dur).toFixed(2)}s`,
      opacity: (0.32 + intensity * 0.38 + Math.random() * 0.16).toFixed(2),
    })
  }
  return out
}

function Rain({ intensity }: { intensity: number }) {
  const drops = React.useState(() => makeRain(intensity))[0]
  return React.createElement('div', { className: 'ws-layer' },
    drops.map((d, i) => React.createElement('span', { key: `r${i}`, className: 'ws-rain', style: d })),
  )
}

function makeSnow(intensity: number): Array<Record<string, string>> {
  const count = Math.round(22 + intensity * 58)
  const out: Array<Record<string, string>> = []
  for (let i = 0; i < count; i++) {
    const s = 3 + Math.random() * 5
    const dur = (3 + (1 - intensity) * 4) * (0.7 + Math.random() * 0.7)
    out.push({
      left: `${Math.random() * 100}%`,
      width: `${s.toFixed(1)}px`,
      height: `${s.toFixed(1)}px`,
      animationDuration: `${dur.toFixed(2)}s`,
      animationDelay: `${(-Math.random() * dur).toFixed(2)}s`,
      opacity: (0.5 + Math.random() * 0.4).toFixed(2),
    })
  }
  return out
}

function Snow({ intensity }: { intensity: number }) {
  const flakes = React.useState(() => makeSnow(intensity))[0]
  return React.createElement('div', { className: 'ws-layer' },
    flakes.map((f, i) => React.createElement('span', { key: `f${i}`, className: 'ws-snow', style: f })),
  )
}

function makeStars(): Array<Record<string, string>> {
  const out: Array<Record<string, string>> = []
  for (let i = 0; i < 70; i++) {
    const s = 1 + Math.random() * 2
    out.push({
      left: `${Math.random() * 100}%`,
      top: `${Math.random() * 60}%`,
      width: `${s.toFixed(1)}px`,
      height: `${s.toFixed(1)}px`,
      animationDuration: `${(2 + Math.random() * 3).toFixed(1)}s`,
      animationDelay: `${(-Math.random() * 3).toFixed(1)}s`,
      opacity: (0.3 + Math.random() * 0.6).toFixed(2),
    })
  }
  return out
}

function Stars() {
  const stars = React.useState(makeStars)[0]
  return React.createElement('div', { className: 'ws-layer' },
    stars.map((s, i) => React.createElement('span', { key: `s${i}`, className: 'ws-star', style: s })),
  )
}

function makeClouds(count: number): Array<Record<string, string>> {
  const out: Array<Record<string, string>> = []
  for (let i = 0; i < count; i++) {
    const w = 90 + Math.random() * 170
    const dur = 55 + Math.random() * 70
    out.push({
      width: `${w.toFixed(0)}px`,
      height: `${(w * 0.42).toFixed(0)}px`,
      top: `${3 + Math.random() * 30}%`,
      animationDuration: `${dur.toFixed(1)}s`,
      animationDelay: `${(-Math.random() * dur).toFixed(1)}s`,
      opacity: (0.34 + Math.random() * 0.3).toFixed(2),
    })
  }
  return out
}

function CloudOne({ style, dark }: { style: Record<string, string>; dark: boolean }) {
  return React.createElement('div', { className: 'ws-cloud' + (dark ? ' dark' : ''), style },
    React.createElement('span', { className: 'puff p1' }),
    React.createElement('span', { className: 'puff p2' }),
    React.createElement('span', { className: 'puff p3' }),
  )
}

function Clouds({ count, dark }: { count: number; dark: boolean }) {
  const clouds = React.useState(() => makeClouds(count))[0]
  return React.createElement('div', { className: 'ws-layer' },
    clouds.map((c, i) => React.createElement(CloudOne, { key: `c${i}`, style: c, dark })),
  )
}

function Sun() {
  return React.createElement('div', { className: 'ws-sun' })
}

function computePhaseShadow(illum: number, f: number): string | null {
  if (illum > 0.96) return null
  if (illum < 0.04) return 'inset 0 0 0 44px rgba(13,15,36,.93)'
  const off = Math.round((1 - illum) * 70) + 4
  const side = f < 0.5 ? 1 : -1
  return `inset ${side * off}px 0 0 ${-Math.round(off * 0.5)}px rgba(13,15,36,.9)`
}

function Moon({ phase }: { phase: number }) {
  const f = ((phase % 1) + 1) % 1
  const illum = (1 - Math.cos(2 * Math.PI * f)) / 2
  const glow = '0 0 34px 10px rgba(205,214,255,.38)'
  const shadow = computePhaseShadow(illum, f)
  const boxShadow = shadow ? `${glow}, ${shadow}` : glow
  return React.createElement('div', { className: 'ws-moon', style: { boxShadow } })
}

function arcToStyle(arc: number | undefined): Record<string, string> {
  const a = typeof arc === 'number' ? (arc < 0 ? 0 : (arc > 1 ? 1 : arc)) : 0.5
  return { left: `${8 + a * 84}%`, top: `${60 - 40 * Math.sin(a * Math.PI)}%` }
}

function Celestial({ isDay, phase, sunArc, moonArc }: { isDay: boolean; phase: number; sunArc?: number; moonArc?: number }) {
  const pos = arcToStyle(isDay ? sunArc : moonArc)
  return React.createElement('div', { className: 'ws-celestial', style: pos },
    isDay ? React.createElement(Sun) : React.createElement(Moon, { phase }),
  )
}

function Fog() {
  return React.createElement('div', { className: 'ws-layer' },
    React.createElement('div', { className: 'ws-fog', style: { top: '-50px' } }),
    React.createElement('div', { className: 'ws-fog', style: { bottom: '20px', animationDelay: '-9s' } }),
    React.createElement('div', { className: 'ws-fog', style: { bottom: '150px', animationDelay: '-15s', opacity: 0.5 } }),
  )
}

function Lightning() {
  return React.createElement('div', { className: 'ws-layer' },
    React.createElement('div', { className: 'ws-flash-screen flash' }),
    React.createElement('div', { className: 'ws-bolt flash' },
      React.createElement('svg', { viewBox: '0 0 600 520', preserveAspectRatio: 'none' },
        React.createElement('polyline', {
          points: '300,0 258,150 318,172 238,330 296,344 248,520',
          fill: 'none', stroke: 'rgba(205,226,255,.92)', strokeWidth: 6, strokeLinejoin: 'round',
          style: { filter: 'drop-shadow(0 0 14px rgba(190,220,255,.9))' },
        }),
        React.createElement('polyline', {
          points: '300,0 258,150 318,172 238,330 296,344 248,520',
          fill: 'none', stroke: 'rgba(255,255,255,.95)', strokeWidth: 2, strokeLinejoin: 'round',
        }),
      ),
    ),
  )
}

function SkyTint({ isDay }: { isDay: boolean }) {
  const background = isDay
    ? 'linear-gradient(180deg, rgba(120,180,255,.12), rgba(180,220,255,.05) 45%, rgba(250,252,255,.02))'
    : 'linear-gradient(180deg, rgba(8,13,34,.24), rgba(14,20,46,.13) 55%, rgba(18,26,56,.1))'
  return React.createElement('div', { className: 'ws-tint', style: { background } })
}

function conditionIcon(condition: string, isDay: boolean): string {
  if (condition === 'clear') return isDay ? '☀️' : '🌙'
  if (condition === 'partly-cloudy') return isDay ? '⛅' : '☁️'
  if (condition === 'cloudy') return '☁️'
  if (condition === 'fog') return '🌫️'
  if (condition === 'rain') return '🌧️'
  if (condition === 'snow') return '❄️'
  if (condition === 'thunderstorm') return '⛈️'
  return '🌤️'
}

function StatusChip({ wx }: { wx: WeatherSnapshot }) {
  const temp = wx.tempC == null ? '' : `${wx.tempC}°C`
  const parts = [wx.location, temp, wx.label].filter((x) => x)
  if (wx.targetLabel) parts.push(wx.targetLabel)
  const moonText = !wx.isDay && wx.moonLabel ? ` · ${wx.moonLabel}` : ''
  return React.createElement('div', { className: 'ws-chip', title: wx.error ?? '' },
    React.createElement('span', { className: 'ws-chip-icon' }, conditionIcon(wx.condition, wx.isDay)),
    React.createElement('span', { className: 'ws-chip-text' }, `${parts.join(' · ')}${moonText}`),
  )
}

function WeatherOverlay({ getWeather, timer }: { getWeather: () => Promise<WeatherSnapshot>; timer: Timer }) {
  const wxState = React.useState<WeatherSnapshot | null>(null)
  const setWx = wxState[1]
  const boltState = React.useState(0)
  const boltKey = boltState[0]
  const setBoltKey = boltState[1]

  React.useEffect(() => {
    let alive = true
    const refresh = () => { getWeather().then((data) => { if (alive && data && data.ok) setWx(data) }).catch(() => {}) }
    refresh()
    const dispose = timer.interval(refresh, 15000)
    return () => { alive = false; dispose() }
  }, [])

  const condition = wx ? wx.condition : null
  React.useEffect(() => {
    if (condition !== 'thunderstorm') return
    return timer.interval(() => setBoltKey((k) => k + 1), 6000)
  }, [condition])

  if (!wx) return React.createElement('div', { className: 'ws-sky' })

  const isDay = wx.isDay
  const cond = wx.condition
  const intensity = typeof wx.intensity === 'number' ? wx.intensity : 0
  const skyClear = cond === 'clear' || cond === 'partly-cloudy'
  const kids: React.ReactElement[] = []

  kids.push(React.createElement(SkyTint, { key: 'tint', isDay }))
  if (!isDay && skyClear) kids.push(React.createElement(Stars, { key: 'stars' }))
  if (skyClear) kids.push(React.createElement(Celestial, { key: 'cel', isDay, phase: wx.moonPhase || 0, sunArc: wx.sunArc, moonArc: wx.moonArc }))

  if (cond === 'partly-cloudy') kids.push(React.createElement(Clouds, { key: 'clouds', count: 3, dark: false }))
  else if (cond === 'cloudy') kids.push(React.createElement(Clouds, { key: 'clouds', count: 6, dark: false }))
  else if (cond === 'thunderstorm') kids.push(React.createElement(Clouds, { key: 'clouds', count: 6, dark: true }))

  if (cond === 'rain') kids.push(React.createElement(Rain, { key: `rain-${Math.round(intensity * 20)}`, intensity }))
  else if (cond === 'snow') kids.push(React.createElement(Snow, { key: `snow-${Math.round(intensity * 20)}`, intensity }))
  else if (cond === 'thunderstorm') {
    kids.push(React.createElement(Rain, { key: 'tstorm-rain', intensity: Math.max(intensity, 0.6) }))
    kids.push(React.createElement(Lightning, { key: `bolt-${boltKey}` }))
  }

  if (cond === 'fog') kids.push(React.createElement(Fog, { key: 'fog' }))

  kids.push(React.createElement(StatusChip, { key: 'chip', wx }))

  return React.createElement('div', { className: 'ws-sky' }, kids)
}

/** Cordis plugin name. */
export const name = 'weather-sky-client'
/** Hard dependencies for the browser half. */
export const inject = ['slots', 'remote', 'timer']

export function apply(ctx: Context): void {
  // Inject this package's stylesheet; removed on unload.
  const tag = document.createElement('style')
  tag.textContent = CSS
  document.head.append(tag)
  ctx.effect(() => () => tag.remove(), 'weather-sky: styles')

  const slots = ctx.get('slots') as { inject?: (key: string, cb: () => unknown) => void; register?: (opts: unknown, render: () => unknown) => unknown } | undefined
  if (slots === undefined || typeof slots.inject !== 'function') return
  const timer = ctx.get('timer') as Timer | undefined
  if (timer === undefined) return
  const remote = ctx.get('remote') as { weatherSky?: { getWeather: () => Promise<WeatherSnapshot> } } | undefined
  const getWeather = remote?.weatherSky?.getWeather?.bind(remote.weatherSky)
  if (getWeather === undefined) return

  slots.inject('shell.overlay', () => (slots.register as (opts: unknown, render: () => unknown) => unknown)(
    { name: 'shell.overlay', id: 'weather-sky', order: -100 },
    () => React.createElement(WeatherOverlay, { getWeather, timer }),
  ))
}
